version: '3'
services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=changeMe!
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: ./api
    volumes:
      - ./api:/usr/src/api/
    links:
      - database
    depends_on:
      - database
  nginx:
    restart: always
    build: ./nginx
    ports:
      - '3050:80'
    depends_on:
      - api
volumes:
  pgdata:
    
