version: '3'
services:
  database:
    image: postgres:latest
    restart: always
    env_file:
      - api/.env.dist
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: ./api
    env_file:
      - api/.env.dist
    volumes:
      - ./api:/usr/src/api/
      - /usr/src/api/node_modules
    links:
      - database
    depends_on:
      - database
  client:
    build: ./client
    env_file:
      - ./client/.env
    volumes:
      - ./client:/usr/src/client
      - /usr/src/client/node_modules
    links:
      - database
    depends_on:
      - database
  nginx:
    restart: always
    build: ./nginx
    ports:
      - '3050:80'
    depends_on:
      - api
      - client
      - database
volumes:
  pgdata:
    
