version: '3'
services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=seo
    ports:
      - "5432:5432"
    volumes:
      - seodata:/var/lib/postgresql/data
  server:
    build: ./server
    ports:
      - "7000:7000"
    volumes:
      - ./server:/usr/src/server/
      - /usr/src/server/node_modules
    links:
      - database
    depends_on:
      - database
volumes:
  seodata:
    
