version: '3'
services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=seo
    ports:
      - "5432:5432"
    volumes:
      - seodata:/var/lib/postgresql/data
  server:
    build: ./server
    ports:
      - "7000:7000"
    depends_on:
      - database
    environment:
            - CHOKIDAR_USEPOLLING=true
volumes:
  seodata:
    
